export interface Listing {
  id: string
  title: string
  location: string
  city: string
  district?: string
  price: number
  imageUrl: string
  images?: string[]
  videoUrl?: string | null
  isFavorite: boolean
  breed: string
  priceType: string
  category: "buyukbas" | "kucukbas"
  age?: string
  weight?: string
  earTag?: string
  gender?: string
  description?: string
  sellerName?: string
  sellerPhone?: string
  createdAt?: string
}

// Image URLs for livestock - using reliable CDN sources
const CATTLE_IMAGES = {
  simental: "https://images.pexels.com/photos/422218/pexels-photo-422218.jpeg?auto=compress&cs=tinysrgb&w=800",
  simental2: "https://images.pexels.com/photos/735968/pexels-photo-735968.jpeg?auto=compress&cs=tinysrgb&w=800",
  holstein: "https://images.pexels.com/photos/162240/bull-calf-heifer-beef-162240.jpeg?auto=compress&cs=tinysrgb&w=800",
  holstein2: "https://images.pexels.com/photos/2165688/pexels-photo-2165688.jpeg?auto=compress&cs=tinysrgb&w=800",
  brownSwiss: "https://images.pexels.com/photos/458991/pexels-photo-458991.jpeg?auto=compress&cs=tinysrgb&w=800",
  angus: "https://images.pexels.com/photos/457447/pexels-photo-457447.jpeg?auto=compress&cs=tinysrgb&w=800",
  angus2: "https://images.pexels.com/photos/2252618/pexels-photo-2252618.jpeg?auto=compress&cs=tinysrgb&w=800",
  jersey: "https://images.pexels.com/photos/936461/pexels-photo-936461.jpeg?auto=compress&cs=tinysrgb&w=800",
  cow: "https://images.pexels.com/photos/1308123/pexels-photo-1308123.jpeg?auto=compress&cs=tinysrgb&w=800",
}

const SHEEP_IMAGES = {
  merino: "https://images.pexels.com/photos/288621/pexels-photo-288621.jpeg?auto=compress&cs=tinysrgb&w=800",
  sheep: "https://images.pexels.com/photos/693776/pexels-photo-693776.jpeg?auto=compress&cs=tinysrgb&w=800",
  sheep2: "https://images.pexels.com/photos/1447349/pexels-photo-1447349.jpeg?auto=compress&cs=tinysrgb&w=800",
  lamb: "https://images.pexels.com/photos/2651822/pexels-photo-2651822.jpeg?auto=compress&cs=tinysrgb&w=800",
  ram: "https://images.pexels.com/photos/6469/red-animal-farm-countryside.jpg?auto=compress&cs=tinysrgb&w=800",
}

export const demoListings: Listing[] = [
  {
    id: "1",
    title: "Simental Boğa",
    location: "Konya, Karatay",
    city: "Konya",
    district: "Karatay",
    price: 32500,
    imageUrl: CATTLE_IMAGES.simental,
    images: [CATTLE_IMAGES.simental, CATTLE_IMAGES.simental2, CATTLE_IMAGES.cow],
    videoUrl: "https://www.w3schools.com/html/mov_bbb.mp4",
    isFavorite: false,
    breed: "simental",
    priceType: "sabit",
    category: "buyukbas",
    age: "2.5 Yaş",
    weight: "650 kg",
    earTag: "TR123456789",
    gender: "erkek",
    description: "Sağlıklı, aşıları tam, veteriner kontrolünden geçmiş simental boğa. Damızlık olarak idealdir.",
    sellerName: "Mehmet Yılmaz",
    sellerPhone: "0532 123 45 67",
    createdAt: "2024-01-15",
  },
  {
    id: "2",
    title: "Simental İnek",
    location: "Konya, Meram",
    city: "Konya",
    district: "Meram",
    price: 28000,
    imageUrl: CATTLE_IMAGES.simental2,
    images: [CATTLE_IMAGES.simental2, CATTLE_IMAGES.simental],
    videoUrl: null,
    isFavorite: true,
    breed: "simental",
    priceType: "pazarlik",
    category: "buyukbas",
    age: "4 Yaş",
    weight: "520 kg",
    earTag: "TR987654321",
    gender: "disi",
    description: "Günlük 25 litre süt veren simental inek. 2 buzağı yapmış, sağlıklı.",
    sellerName: "Ali Kaya",
    sellerPhone: "0533 987 65 43",
    createdAt: "2024-01-14",
  },
  {
    id: "3",
    title: "Holstein İnek",
    location: "İzmir, Tire",
    city: "İzmir",
    district: "Tire",
    price: 35000,
    imageUrl: CATTLE_IMAGES.holstein,
    images: [CATTLE_IMAGES.holstein, CATTLE_IMAGES.holstein2, CATTLE_IMAGES.cow],
    videoUrl: "https://www.w3schools.com/html/movie.mp4",
    isFavorite: false,
    breed: "holstein",
    priceType: "sabit",
    category: "buyukbas",
    age: "3 Yaş",
    weight: "580 kg",
    earTag: "TR456789123",
    gender: "disi",
    description: "Yüksek süt verimi olan holstein inek. Günlük 30+ litre süt.",
    sellerName: "Hasan Demir",
    sellerPhone: "0535 456 78 90",
    createdAt: "2024-01-13",
  },
  {
    id: "4",
    title: "Montofon Düve",
    location: "Bursa, İnegöl",
    city: "Bursa",
    district: "İnegöl",
    price: 24500,
    imageUrl: CATTLE_IMAGES.brownSwiss,
    images: [CATTLE_IMAGES.brownSwiss, CATTLE_IMAGES.cow],
    videoUrl: null,
    isFavorite: false,
    breed: "montofon",
    priceType: "pazarlik",
    category: "buyukbas",
    age: "1.5 Yaş",
    weight: "380 kg",
    earTag: "TR789123456",
    gender: "disi",
    description: "Gebe düve, 4 aylık gebe. Sağlıklı ve bakımlı.",
    sellerName: "Osman Çelik",
    sellerPhone: "0536 789 12 34",
    createdAt: "2024-01-12",
  },
  {
    id: "5",
    title: "Angus Tosun",
    location: "Ankara, Polatlı",
    city: "Ankara",
    district: "Polatlı",
    price: 42000,
    imageUrl: CATTLE_IMAGES.angus,
    images: [CATTLE_IMAGES.angus, CATTLE_IMAGES.angus2, CATTLE_IMAGES.cow],
    videoUrl: null,
    isFavorite: true,
    breed: "angus",
    priceType: "sabit",
    category: "buyukbas",
    age: "2 Yaş",
    weight: "720 kg",
    earTag: "TR321654987",
    gender: "erkek",
    description: "Et ırkı Angus tosun. Besiye uygun, hızlı gelişen.",
    sellerName: "Mustafa Öz",
    sellerPhone: "0537 321 65 49",
    createdAt: "2024-01-11",
  },
  {
    id: "6",
    title: "Jersey İnek",
    location: "Balıkesir, Bandırma",
    city: "Balıkesir",
    district: "Bandırma",
    price: 31000,
    imageUrl: CATTLE_IMAGES.jersey,
    images: [CATTLE_IMAGES.jersey],
    videoUrl: null,
    isFavorite: false,
    breed: "jersey",
    priceType: "sabit",
    category: "buyukbas",
    age: "5 Yaş",
    weight: "420 kg",
    earTag: "TR654987321",
    gender: "disi",
    description: "Yüksek yağ oranında süt veren Jersey inek.",
    sellerName: "Ahmet Yıldız",
    sellerPhone: "0538 654 98 73",
    createdAt: "2024-01-10",
  },
  {
    id: "7",
    title: "Merinos Koç",
    location: "Konya, Ereğli",
    city: "Konya",
    district: "Ereğli",
    price: 8500,
    imageUrl: SHEEP_IMAGES.ram,
    images: [SHEEP_IMAGES.ram, SHEEP_IMAGES.merino],
    videoUrl: "https://www.w3schools.com/html/mov_bbb.mp4",
    isFavorite: false,
    breed: "merinos",
    priceType: "sabit",
    category: "kucukbas",
    age: "3 Yaş",
    weight: "95 kg",
    earTag: "TR111222333",
    gender: "erkek",
    description: "Damızlık merinos koç. Kaliteli yün ve iyi genetik.",
    sellerName: "İbrahim Arslan",
    sellerPhone: "0539 111 22 33",
    createdAt: "2024-01-09",
  },
  {
    id: "8",
    title: "Akkaraman Koyun",
    location: "Ankara, Çubuk",
    city: "Ankara",
    district: "Çubuk",
    price: 4500,
    imageUrl: SHEEP_IMAGES.sheep,
    images: [SHEEP_IMAGES.sheep],
    videoUrl: null,
    isFavorite: false,
    breed: "akkaraman",
    priceType: "pazarlik",
    category: "kucukbas",
    age: "2 Yaş",
    weight: "55 kg",
    earTag: "TR444555666",
    gender: "disi",
    description: "Yerli akkaraman koyun. İkiz doğum yapıyor.",
    sellerName: "Hüseyin Koç",
    sellerPhone: "0540 444 55 66",
    createdAt: "2024-01-08",
  },
  {
    id: "9",
    title: "Kıvırcık Kuzu",
    location: "Balıkesir, Edremit",
    city: "Balıkesir",
    district: "Edremit",
    price: 3200,
    imageUrl: SHEEP_IMAGES.lamb,
    images: [SHEEP_IMAGES.lamb, SHEEP_IMAGES.sheep2],
    videoUrl: null,
    isFavorite: true,
    breed: "kivircik",
    priceType: "sabit",
    category: "kucukbas",
    age: "6 Aylık",
    weight: "32 kg",
    earTag: "TR777888999",
    gender: "erkek",
    description: "Lezzetli eti ile meşhur kıvırcık kuzusu.",
    sellerName: "Kemal Şen",
    sellerPhone: "0541 777 88 99",
    createdAt: "2024-01-07",
  },
  {
    id: "10",
    title: "Merinos Koyun",
    location: "Manisa, Akhisar",
    city: "Manisa",
    district: "Akhisar",
    price: 6000,
    imageUrl: SHEEP_IMAGES.merino,
    images: [SHEEP_IMAGES.merino],
    videoUrl: null,
    isFavorite: false,
    breed: "merinos",
    priceType: "pazarlik",
    category: "kucukbas",
    age: "2.5 Yaş",
    weight: "68 kg",
    earTag: "TR000111222",
    gender: "disi",
    description: "Yüksek kalite yün veren merinos koyun.",
    sellerName: "Recep Aydın",
    sellerPhone: "0542 000 11 22",
    createdAt: "2024-01-06",
  },
  {
    id: "11",
    title: "Simental Düve",
    location: "Kayseri, Develi",
    city: "Kayseri",
    district: "Develi",
    price: 26000,
    imageUrl: CATTLE_IMAGES.simental2,
    images: [CATTLE_IMAGES.simental2],
    videoUrl: null,
    isFavorite: false,
    breed: "simental",
    priceType: "pazarlik",
    category: "buyukbas",
    age: "1.5 Yaş",
    weight: "420 kg",
    earTag: "TR112233445",
    gender: "disi",
    description: "Gebe simental düve, 3 aylık gebe.",
    sellerName: "Veli Karaca",
    createdAt: "2024-01-05",
  },
  {
    id: "12",
    title: "Holstein Boğa",
    location: "Samsun, Bafra",
    city: "Samsun",
    district: "Bafra",
    price: 38000,
    imageUrl: CATTLE_IMAGES.holstein,
    images: [CATTLE_IMAGES.holstein],
    videoUrl: "https://www.w3schools.com/html/mov_bbb.mp4",
    isFavorite: false,
    breed: "holstein",
    priceType: "sabit",
    category: "buyukbas",
    age: "2 Yaş",
    weight: "680 kg",
    earTag: "TR556677889",
    gender: "erkek",
    description: "Damızlık Holstein boğa, genetiği çok iyi.",
    sellerName: "Cengiz Yurt",
    createdAt: "2024-01-04",
  },
  {
    id: "13",
    title: "Yerli Kara İnek",
    location: "Erzurum, Pasinler",
    city: "Erzurum",
    district: "Pasinler",
    price: 18000,
    imageUrl: CATTLE_IMAGES.angus,
    images: [CATTLE_IMAGES.angus],
    videoUrl: null,
    isFavorite: false,
    breed: "yerli",
    priceType: "pazarlik",
    category: "buyukbas",
    age: "5 Yaş",
    weight: "450 kg",
    earTag: "TR998877665",
    gender: "disi",
    description: "Yerli kara inek, dayanıklı ve sağlıklı.",
    sellerName: "Şükrü Dağ",
    createdAt: "2024-01-03",
  },
  {
    id: "14",
    title: "Montofon Boğa",
    location: "Afyon, Sandıklı",
    city: "Afyon",
    district: "Sandıklı",
    price: 45000,
    imageUrl: CATTLE_IMAGES.brownSwiss,
    images: [CATTLE_IMAGES.brownSwiss],
    videoUrl: null,
    isFavorite: true,
    breed: "montofon",
    priceType: "sabit",
    category: "buyukbas",
    age: "3 Yaş",
    weight: "780 kg",
    earTag: "TR443322110",
    gender: "erkek",
    description: "Damızlık Montofon boğa, çok güçlü.",
    sellerName: "Halil Tepe",
    createdAt: "2024-01-02",
  },
  {
    id: "15",
    title: "Jersey Düve",
    location: "Çanakkale, Biga",
    city: "Çanakkale",
    district: "Biga",
    price: 22000,
    imageUrl: CATTLE_IMAGES.jersey,
    images: [CATTLE_IMAGES.jersey],
    videoUrl: "https://www.w3schools.com/html/movie.mp4",
    isFavorite: false,
    breed: "jersey",
    priceType: "pazarlik",
    category: "buyukbas",
    age: "1 Yaş",
    weight: "320 kg",
    earTag: "TR667788990",
    gender: "disi",
    description: "Genç Jersey düve, süt ırkı.",
    sellerName: "Tamer Gül",
    createdAt: "2024-01-01",
  },
  {
    id: "16",
    title: "Simental İkiz Buzağı",
    location: "Konya, Çumra",
    city: "Konya",
    district: "Çumra",
    price: 12000,
    imageUrl: CATTLE_IMAGES.simental,
    images: [CATTLE_IMAGES.simental],
    videoUrl: null,
    isFavorite: false,
    breed: "simental",
    priceType: "sabit",
    category: "buyukbas",
    age: "3 Aylık",
    weight: "85 kg",
    earTag: "TR101010101",
    gender: "erkek",
    description: "Simental ikiz buzağılar, çok sağlıklı.",
    sellerName: "Orhan Ak",
    createdAt: "2023-12-30",
  },
  {
    id: "17",
    title: "Saanen Keçi",
    location: "Aydın, Nazilli",
    city: "Aydın",
    district: "Nazilli",
    price: 5500,
    imageUrl: SHEEP_IMAGES.merino,
    images: [SHEEP_IMAGES.merino],
    videoUrl: null,
    isFavorite: false,
    breed: "saanen",
    priceType: "sabit",
    category: "kucukbas",
    age: "2 Yaş",
    weight: "65 kg",
    earTag: "TR202020202",
    gender: "disi",
    description: "Yüksek süt verimi olan Saanen keçi.",
    sellerName: "Celal Ova",
    createdAt: "2023-12-29",
  },
  {
    id: "18",
    title: "Kilis Keçisi",
    location: "Gaziantep, Nizip",
    city: "Gaziantep",
    district: "Nizip",
    price: 4200,
    imageUrl: SHEEP_IMAGES.sheep,
    images: [SHEEP_IMAGES.sheep],
    videoUrl: "https://www.w3schools.com/html/mov_bbb.mp4",
    isFavorite: false,
    breed: "kilis",
    priceType: "pazarlik",
    category: "kucukbas",
    age: "3 Yaş",
    weight: "58 kg",
    earTag: "TR303030303",
    gender: "disi",
    description: "Kilis keçisi, süt ve et verimi yüksek.",
    sellerName: "Bekir Taş",
    createdAt: "2023-12-28",
  },
  {
    id: "19",
    title: "İvesi Koyun",
    location: "Şanlıurfa, Siverek",
    city: "Şanlıurfa",
    district: "Siverek",
    price: 5800,
    imageUrl: SHEEP_IMAGES.ram,
    images: [SHEEP_IMAGES.ram],
    videoUrl: null,
    isFavorite: true,
    breed: "ivesi",
    priceType: "sabit",
    category: "kucukbas",
    age: "2.5 Yaş",
    weight: "72 kg",
    earTag: "TR404040404",
    gender: "disi",
    description: "İvesi koyun, yüksek süt verimi.",
    sellerName: "Şeref Kır",
    createdAt: "2023-12-27",
  },
  {
    id: "20",
    title: "Morkaraman Koç",
    location: "Van, Erciş",
    city: "Van",
    district: "Erciş",
    price: 9500,
    imageUrl: SHEEP_IMAGES.lamb,
    images: [SHEEP_IMAGES.lamb],
    videoUrl: null,
    isFavorite: false,
    breed: "morkaraman",
    priceType: "pazarlik",
    category: "kucukbas",
    age: "4 Yaş",
    weight: "105 kg",
    earTag: "TR505050505",
    gender: "erkek",
    description: "Damızlık Morkaraman koç, güçlü genetik.",
    sellerName: "Serhat Yıldırım",
    createdAt: "2023-12-26",
  },
  {
    id: "21",
    title: "Limuzin Boğa",
    location: "Eskişehir, Odunpazarı",
    city: "Eskişehir",
    district: "Odunpazarı",
    price: 55000,
    imageUrl: CATTLE_IMAGES.angus,
    images: [CATTLE_IMAGES.angus],
    videoUrl: null,
    isFavorite: false,
    breed: "limuzin",
    priceType: "sabit",
    category: "buyukbas",
    age: "2.5 Yaş",
    weight: "820 kg",
    earTag: "TR606060606",
    gender: "erkek",
    description: "Et ırkı Limuzin boğa, yüksek et verimi.",
    sellerName: "Ferhat Yaman",
    createdAt: "2023-12-25",
  },
  {
    id: "22",
    title: "Simental Gebe İnek",
    location: "Denizli, Acıpayam",
    city: "Denizli",
    district: "Acıpayam",
    price: 34000,
    imageUrl: CATTLE_IMAGES.simental2,
    images: [CATTLE_IMAGES.simental2],
    videoUrl: "https://www.w3schools.com/html/mov_bbb.mp4",
    isFavorite: false,
    breed: "simental",
    priceType: "pazarlik",
    category: "buyukbas",
    age: "4 Yaş",
    weight: "550 kg",
    earTag: "TR707070707",
    gender: "disi",
    description: "6 aylık gebe simental inek, 3. buzağısına gebe.",
    sellerName: "Necati Eren",
    createdAt: "2023-12-24",
  },
  {
    id: "23",
    title: "Holstein Düve",
    location: "Tekirdağ, Çorlu",
    city: "Tekirdağ",
    district: "Çorlu",
    price: 27000,
    imageUrl: CATTLE_IMAGES.holstein,
    images: [CATTLE_IMAGES.holstein],
    videoUrl: null,
    isFavorite: false,
    breed: "holstein",
    priceType: "sabit",
    category: "buyukbas",
    age: "1.5 Yaş",
    weight: "400 kg",
    earTag: "TR808080808",
    gender: "disi",
    description: "Süt ırkı Holstein düve, henüz tohumlanmamış.",
    sellerName: "Zafer Kılıç",
    createdAt: "2023-12-23",
  },
  {
    id: "24",
    title: "Charolais Tosun",
    location: "Edirne, Keşan",
    city: "Edirne",
    district: "Keşan",
    price: 48000,
    imageUrl: CATTLE_IMAGES.brownSwiss,
    images: [CATTLE_IMAGES.brownSwiss],
    videoUrl: null,
    isFavorite: true,
    breed: "charolais",
    priceType: "sabit",
    category: "buyukbas",
    age: "2 Yaş",
    weight: "750 kg",
    earTag: "TR909090909",
    gender: "erkek",
    description: "Fransız et ırkı Charolais tosun, çok kaliteli.",
    sellerName: "Burhan Aksoy",
    createdAt: "2023-12-22",
  },
  {
    id: "25",
    title: "Jersey Gebe Düve",
    location: "Muğla, Fethiye",
    city: "Muğla",
    district: "Fethiye",
    price: 25000,
    imageUrl: CATTLE_IMAGES.jersey,
    images: [CATTLE_IMAGES.jersey],
    videoUrl: null,
    isFavorite: false,
    breed: "jersey",
    priceType: "pazarlik",
    category: "buyukbas",
    age: "2 Yaş",
    weight: "350 kg",
    earTag: "TR010101010",
    gender: "disi",
    description: "3 aylık gebe Jersey düve.",
    sellerName: "Soner Deniz",
    createdAt: "2023-12-21",
  },
  {
    id: "26",
    title: "Angus İnek",
    location: "Kırklareli, Lüleburgaz",
    city: "Kırklareli",
    district: "Lüleburgaz",
    price: 38000,
    imageUrl: CATTLE_IMAGES.angus,
    images: [CATTLE_IMAGES.angus],
    videoUrl: "https://www.w3schools.com/html/movie.mp4",
    isFavorite: false,
    breed: "angus",
    priceType: "sabit",
    category: "buyukbas",
    age: "3 Yaş",
    weight: "580 kg",
    earTag: "TR121212121",
    gender: "disi",
    description: "Black Angus inek, damızlık uygun.",
    sellerName: "Levent Yurt",
    createdAt: "2023-12-20",
  },
  {
    id: "27",
    title: "Simental 5'li Paket",
    location: "Bolu, Merkez",
    city: "Bolu",
    district: "Merkez",
    price: 145000,
    imageUrl: CATTLE_IMAGES.simental,
    images: [CATTLE_IMAGES.simental],
    videoUrl: null,
    isFavorite: false,
    breed: "simental",
    priceType: "sabit",
    category: "buyukbas",
    age: "Çeşitli",
    weight: "Çeşitli",
    earTag: "TR131313131",
    gender: "karisik",
    description: "5 adet simental inek paketi, toplu satış.",
    sellerName: "Kamil Boz",
    createdAt: "2023-12-19",
  },
  {
    id: "28",
    title: "Holstein Buzağı",
    location: "Sakarya, Adapazarı",
    city: "Sakarya",
    district: "Adapazarı",
    price: 9500,
    imageUrl: CATTLE_IMAGES.holstein,
    images: [CATTLE_IMAGES.holstein],
    videoUrl: null,
    isFavorite: false,
    breed: "holstein",
    priceType: "pazarlik",
    category: "buyukbas",
    age: "4 Aylık",
    weight: "120 kg",
    earTag: "TR141414141",
    gender: "disi",
    description: "Dişi Holstein buzağı, süt genetiği çok iyi.",
    sellerName: "Yaşar Kara",
    createdAt: "2023-12-18",
  },
  {
    id: "29",
    title: "Kıvırcık Koç",
    location: "Çanakkale, Ezine",
    city: "Çanakkale",
    district: "Ezine",
    price: 7500,
    imageUrl: SHEEP_IMAGES.lamb,
    images: [SHEEP_IMAGES.lamb],
    videoUrl: "https://www.w3schools.com/html/mov_bbb.mp4",
    isFavorite: false,
    breed: "kivircik",
    priceType: "sabit",
    category: "kucukbas",
    age: "2.5 Yaş",
    weight: "78 kg",
    earTag: "TR151515151",
    gender: "erkek",
    description: "Damızlık kıvırcık koç, meşhur Ezine cinsi.",
    sellerName: "Rıfat Acar",
    createdAt: "2023-12-17",
  },
  {
    id: "30",
    title: "Akkaraman Sürüsü",
    location: "Konya, Cihanbeyli",
    city: "Konya",
    district: "Cihanbeyli",
    price: 85000,
    imageUrl: SHEEP_IMAGES.sheep,
    images: [SHEEP_IMAGES.sheep],
    videoUrl: null,
    isFavorite: true,
    breed: "akkaraman",
    priceType: "pazarlik",
    category: "kucukbas",
    age: "Çeşitli",
    weight: "Çeşitli",
    earTag: "Çeşitli",
    gender: "karisik",
    description: "20 başlık akkaraman koyun sürüsü, 2 koç dahil.",
    sellerName: "Durmuş Ali",
    createdAt: "2023-12-16",
  },
  {
    id: "31",
    title: "Sakız Koyunu",
    location: "İzmir, Çeşme",
    city: "İzmir",
    district: "Çeşme",
    price: 6500,
    imageUrl: SHEEP_IMAGES.merino,
    images: [SHEEP_IMAGES.merino],
    videoUrl: null,
    isFavorite: false,
    breed: "sakiz",
    priceType: "sabit",
    category: "kucukbas",
    age: "2 Yaş",
    weight: "62 kg",
    earTag: "TR161616161",
    gender: "disi",
    description: "Ege bölgesi sakız koyunu, çoğuz doğurgan.",
    sellerName: "Fikret Turan",
    createdAt: "2023-12-15",
  },
  {
    id: "32",
    title: "Tuj Koyunu",
    location: "Ardahan, Merkez",
    city: "Ardahan",
    district: "Merkez",
    price: 4800,
    imageUrl: SHEEP_IMAGES.sheep,
    images: [SHEEP_IMAGES.sheep],
    videoUrl: null,
    isFavorite: false,
    breed: "tuj",
    priceType: "pazarlik",
    category: "kucukbas",
    age: "3 Yaş",
    weight: "58 kg",
    earTag: "TR171717171",
    gender: "disi",
    description: "Doğu Anadolu tuj koyunu, soğuğa dayanıklı.",
    sellerName: "Metin Bulut",
    createdAt: "2023-12-14",
  },
  {
    id: "33",
    title: "Kilis Keçisi Sürüsü",
    location: "Hatay, Reyhanlı",
    city: "Hatay",
    district: "Reyhanlı",
    price: 42000,
    imageUrl: SHEEP_IMAGES.ram,
    images: [SHEEP_IMAGES.ram],
    videoUrl: "https://www.w3schools.com/html/movie.mp4",
    isFavorite: false,
    breed: "kilis",
    priceType: "sabit",
    category: "kucukbas",
    age: "Çeşitli",
    weight: "Çeşitli",
    earTag: "Çeşitli",
    gender: "karisik",
    description: "10 başlık Kilis keçisi sürüsü.",
    sellerName: "Selim Güneş",
    createdAt: "2023-12-13",
  },
  {
    id: "34",
    title: "Ankara Keçisi",
    location: "Ankara, Beypazarı",
    city: "Ankara",
    district: "Beypazarı",
    price: 3500,
    imageUrl: SHEEP_IMAGES.merino,
    images: [SHEEP_IMAGES.merino],
    videoUrl: null,
    isFavorite: false,
    breed: "ankara",
    priceType: "pazarlik",
    category: "kucukbas",
    age: "2 Yaş",
    weight: "42 kg",
    earTag: "TR181818181",
    gender: "disi",
    description: "Tiftik için ideal Ankara keçisi.",
    sellerName: "Nuri Şahin",
    createdAt: "2023-12-12",
  },
  {
    id: "35",
    title: "Hemşin Koyunu",
    location: "Rize, Çamlıhemşin",
    city: "Rize",
    district: "Çamlıhemşin",
    price: 5200,
    imageUrl: SHEEP_IMAGES.lamb,
    images: [SHEEP_IMAGES.lamb],
    videoUrl: null,
    isFavorite: true,
    breed: "hemsin",
    priceType: "sabit",
    category: "kucukbas",
    age: "2 Yaş",
    weight: "48 kg",
    earTag: "TR191919191",
    gender: "disi",
    description: "Karadeniz yaylası Hemşin koyunu.",
    sellerName: "Cemal Deniz",
    createdAt: "2023-12-11",
  },
  {
    id: "36",
    title: "Dağlıç Koç",
    location: "Afyon, Emirdağ",
    city: "Afyon",
    district: "Emirdağ",
    price: 8200,
    imageUrl: SHEEP_IMAGES.ram,
    images: [SHEEP_IMAGES.ram],
    videoUrl: null,
    isFavorite: false,
    breed: "daglic",
    priceType: "pazarlik",
    category: "kucukbas",
    age: "3 Yaş",
    weight: "88 kg",
    earTag: "TR202020203",
    gender: "erkek",
    description: "Güçlü damızlık Dağlıç koç.",
    sellerName: "Hayri Özkan",
    createdAt: "2023-12-10",
  },
  {
    id: "37",
    title: "Montofon İnek",
    location: "Kastamonu, Tosya",
    city: "Kastamonu",
    district: "Tosya",
    price: 32000,
    imageUrl: CATTLE_IMAGES.brownSwiss,
    images: [CATTLE_IMAGES.brownSwiss],
    videoUrl: null,
    isFavorite: false,
    breed: "montofon",
    priceType: "sabit",
    category: "buyukbas",
    age: "4 Yaş",
    weight: "520 kg",
    earTag: "TR212121212",
    gender: "disi",
    description: "Süt ve et verimi dengeli Montofon inek.",
    sellerName: "Tahir Gök",
    createdAt: "2023-12-09",
  },
  {
    id: "38",
    title: "Yerli Kara Tosun",
    location: "Tokat, Erbaa",
    city: "Tokat",
    district: "Erbaa",
    price: 28000,
    imageUrl: CATTLE_IMAGES.angus,
    images: [CATTLE_IMAGES.angus],
    videoUrl: "https://www.w3schools.com/html/mov_bbb.mp4",
    isFavorite: false,
    breed: "yerli",
    priceType: "pazarlik",
    category: "buyukbas",
    age: "2 Yaş",
    weight: "520 kg",
    earTag: "TR222222222",
    gender: "erkek",
    description: "Yerli kara tosun, besiye uygun.",
    sellerName: "Bilal Yıldırım",
    createdAt: "2023-12-08",
  },
  {
    id: "39",
    title: "Simental 3'lü İnek",
    location: "Yozgat, Sorgun",
    city: "Yozgat",
    district: "Sorgun",
    price: 92000,
    imageUrl: CATTLE_IMAGES.simental2,
    images: [CATTLE_IMAGES.simental2],
    videoUrl: null,
    isFavorite: false,
    breed: "simental",
    priceType: "sabit",
    category: "buyukbas",
    age: "3-5 Yaş",
    weight: "500-550 kg",
    earTag: "Çeşitli",
    gender: "disi",
    description: "3 adet simental inek, hepsi sağmal.",
    sellerName: "Sedat Korkmaz",
    createdAt: "2023-12-07",
  },
  {
    id: "40",
    title: "Merinos Kuzu",
    location: "Uşak, Banaz",
    city: "Uşak",
    district: "Banaz",
    price: 2800,
    imageUrl: SHEEP_IMAGES.lamb,
    images: [SHEEP_IMAGES.lamb],
    videoUrl: null,
    isFavorite: false,
    breed: "merinos",
    priceType: "pazarlik",
    category: "kucukbas",
    age: "5 Aylık",
    weight: "28 kg",
    earTag: "TR232323232",
    gender: "erkek",
    description: "Merinos kuzu, kurban veya besiye uygun.",
    sellerName: "Kenan Baran",
    createdAt: "2023-12-06",
  },
]

export function getListingById(id: string): Listing | undefined {
  return demoListings.find((listing) => listing.id === id)
}
